name: Build

on:
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.22'
          - '1.23'

    name: Build ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{ matrix.go-version }}

      - run: |
          go build ./...
          go test -run=^$ ./...
