name: Build

on:
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.22'
          - '1.23'

    name: Build ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: ${{ matrix.go-version }}

      - run: |
          go build ./...
          go test -run=^$ ./...
