name: Build

on:
  pull_request:
    branches:
      - 'main'

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - '1.20'
          - '1.21'

    name: Build ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4 # v1
        with:
          go-version-input: ${{ matrix.go-version }}

      - run: |
          go build ./...
          go test -run=^$ ./...
