name: Integration Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Module Tests
    strategy:
      matrix:
        go-version:
          - '1.22'
          - '1.23'

    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - env:
          GOPATH: does not matter
        run: ./integration_test.sh
