name: Integration Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Module Tests
    strategy:
      matrix:
        go-version:
          - '1.21'
          - '1.22'

    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - env:
          GOPATH: does not matter
        run: ./integration_test.sh
