name: Integration Test

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Module Tests
    strategy:
      matrix:
        go-version: ['1.19', '1.20']

    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - env:
          GOPATH: does not matter
        run: ./integration_test.sh
