name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-redirects
      - run: mkdocs gh-deploy --force
