name: Verify

on:
  pull_request:
    branches: ['main']

jobs:
  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.20'
        check-latest: true
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Verify
      run: ./hack/presubmit.sh
